# -*- coding: utf-8 -*-
"""count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

#Python Program to count unique values inside a list

def a(list):
    b = set()

    for value in list:
        b.add(value)

    return len(b)

list1 = [1,2,3,4,2,3,6,7,8,9,10]
answer = a (list1)
print("Number of unique values:", answer)