# -*- coding: utf-8 -*-
"""letter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

#All letters of English Alphabets
def create_alphabet_file(linesize, filename):
    alphabet = 'abcdefghijklmnopqrstuvwxyz'

    with open(filename, 'w') as file:
        for i in range(0, len(alphabet), linesize):
            line = alphabet[i:i+linesize]
            file.write(line + '\n')