# -*- coding: utf-8 -*-
"""series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

# Python program to print the Fibonacci series up to a specified number of term

def fibonacci(n):
    fib_series = [0, 1]

    while len(fib_series) < n:
        fib_series.append(fib_series[-1] + fib_series[-2])

    return fib_series


num_terms = 10
result = fibonacci(num_terms)

print(f"Fibonacci series up to {num_terms} terms: {result}")