# -*- coding: utf-8 -*-
"""sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G10h_JMbGmS3S_03zFZHv5RMbSe8G6H
"""

#Python program to display the sum of n numbers using a list

def sum_of_numbers(numbers):
    return sum(numbers)


user_numbers = [int(x) for x in input("Enter numbers separated by spaces: ").split()]
result = sum_of_numbers(user_numbers)
print(f"The sum of the numbers is: {result}")